language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
# command to run tests
script:
  coverage run --source='trololo' trololo/manage.py test trololo/
notifications:
  slack:
    rooms:
      - xmig:Do2DjKxRl61PQuxEEjpwLAiM#tracking_system_dev
